name: WinterVillage-RestartManagement
version: 8.0-SNAPSHOT
main: de.wintervillage.restart.paper.WinterVillagePaper
author: Voldechse
api-version: "1.21"
dependencies:
  server:
    CloudNet-Bridge:
      load: BEFORE
      required: true